# Generated by Django 3.0 on 2025-11-06 16:24

from django.db import migrations


def save_data_migration_profile(apps, schema_editor):
    old_Profile = apps.get_model('oc_lettings_site', 'Profile')
    new_Profile = apps.get_model('profiles', 'Profile')
    for profile in old_Profile.objects.all():
        new_Profile.objects.create(
            id=profile.id,
            user=profile.user,
            favorite_city=profile.favorite_city
        )

class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(save_data_migration_profile),
    ]
