# Generated by Django 3.0 on 2025-11-06 14:50

from django.db import migrations

def save_data_migration_adresse(apps, schema_editor):
    old_address = apps.get_model('oc_lettings_site', 'Address')
    new_address = apps.get_model('lettings', 'Address')
    for address in old_address.objects.all():
        new_address.objects.create(
            id=address.id,
            number=address.number,
            street=address.street,
            city=address.city,
            state=address.state,
            zip_code=address.zip_code,
            country_iso_code=address.country_iso_code
        )

def save_data_migration_letting(apps, schema_editor):
    old_letting = apps.get_model('oc_lettings_site', 'Letting')
    new_letting = apps.get_model('lettings', 'Letting')
    new_address = apps.get_model('lettings', 'Address')
    for letting in old_letting.objects.all():
        new_letting.objects.create(
            id=letting.id,
            title=letting.title,
            address=new_address.objects.get(id=letting.address.id)
        )


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(save_data_migration_adresse),
        migrations.RunPython(save_data_migration_letting),
    ]
